ECHO OFF
REM **************************************************************
REM COMMAND SCRIPT USED TO GENERATE THE CRYPTIC-THEME PACKAGE
REM SCAFFOLDING USING SENCHA CMD V5 (BETA).  THIS PACKAGE
REM WILL DEFINE THE THEME USED BY THE CRYPTIC APPLICATION.
REM **************************************************************
ECHO ON

:_SETUP_ENV__
	CALL env_profile.bat
	IF NOT EXIST "%WORKING_DIR%" (
		ECHO THE WORKING DIRECTORY, %WORKING_DIR%, DOES NOT EXIST.  PLEASE UPDATE THE env_profile.bat SCRIPT.
		PAUSE
		GOTO _ABORTED__
	)
	SET PACKAGE=cryptic-theme
	SET WORKSPACE_PATH=%WORKING_DIR%\web
	SET PACKAGE_PATH=%WORKSPACE_PATH%\cryptic
	SET EXT_PATH=%WORKSPACE_PATH%\ext
	SET SCRIPT_PATH=%WORKING_DIR%\scripts\sencha

cd %WORKSPACE_PATH%

:_GENERATE_PACKAGE__
	sencha generate package -type theme %PACKAGE%
	IF %ERRORLEVEL% NEQ 0 (
		PAUSE
		GOTO _ABORTED__
	)
	GOTO _END__
	
:_ABORTED__
	exit /b
	
:_END__
	cd %SCRIPT_PATH%
	ECHO GENERATE COMPLETE
	PAUSE 